### ISSUE TITLE
多次截图内存占用递增

### ISSUE THREAD

**Issue by pePZqFHzJVofRgEDrn5L** [ljf1239848066/lxzhASS#2]
CaptureForm中有static字段maxHeight、maxWidth ，这两个字段会在后面的GetScreen方法中用于new Bitmap。
CaptureForm构造函数中计算maxHeight、maxWidth代码如下
```
            foreach (Screen screen in Screen.AllScreens) {
                maxWidth += screen.Bounds.Width;
                if (screen.Bounds.Height > maxHeight) {
                    maxHeight = screen.Bounds.Height;
                }
            }
```
由于是static的字段MainForm中每次new CaptureForm时maxWidth 都在递增，表现为每次调用截图内存消耗会明显增加，我一开始还以为是内存泄露。

**Comment by lxzh** [comment]
@pePZqFHzJVofRgEDrn5L 我也注意到这个问题，但没找到问题原因，多谢提示。
